before_script:
  - docker info

build_image:
  script:
    - docker build -t promet-client .
cleanup:
  script:
    - docker rm $(docker ps -a -q) 
    - docker rmi $(docker images | grep "^<none>" | awk "{print $3}")
  allow_failure: true  