before_script:
  - docker info

build_image:
  script:
    - docker build -t promet-client .

update_remote:
  variables:
    REPO_NAME: "promet-client-docker"
  script:
    - cd $HOME
    - rm -rf $REPO_NAME.git    
    - git clone --bare http://192.168.177.120:10080/promet/$REPO_NAME.git
    - cd $REPO_NAME.git
    - git push --mirror git@github.com:cutec-chris/$REPO_NAME.git
    - cd ..
    - rm -rf $REPO_NAME.git