before_script:
  - docker info

build_image:
  script:
    - docker build -t promet-client .

update_remote:
  script:
    - cd $HOME
$   - git clone --bare http://192.168.177.120:10080/promet/promet-client-docker.git
$   - cd promet-client-docker.git
$   - git push --mirror https://github.com/cutec-chris/promet-client-docker.git
$   - cd ..
$   - rm -rf promet-client-docker.git