before_script:
  - docker info

build_image:
  script:
    - docker build -t promet-client .

update_remote:
  script:
    - echo "machine github.com" > ~/.netrc
    - echo "        login $" >> ~/.netrc
    - echo "machine github.com" >> ~/.netrc
    - cd $HOME
    - rm -rf promet-client-docker.git    
    - git clone --bare http://192.168.177.120:10080/promet/promet-client-docker.git
    - cd promet-client-docker.git
    - git push --mirror git@github.com:cutec-chris/promet-client-docker.git
    - cd ..
    - rm -rf promet-client-docker.git