before_script:
  - docker info

build_image:
  stage: build 
  script:
    - docker build -t promet-client .

update_remote:
  stage: test
  variables:
    REPO_NAME: "promet-client-docker"
  script:
    - cd $HOME
    - rm -rf $REPO_NAME.git    
    - git clone --bare http://192.168.177.120:10080/promet/$REPO_NAME.git
    - cd $REPO_NAME.git
    - git push --mirror git@github.com:cutec-chris/$REPO_NAME.git
    - cd ..
    - rm -rf $REPO_NAME.git

build_docker:
  stage: deploy 
  script:
    - curl -X POST https://registry.hub.docker.com/u/cutec/promet-client/trigger/e75e9bec-3207-4b33-82ad-99d1157902b7/